### ISSUE TITLE
reading on uninitialized memory may cause undefined behavior

### ISSUE THREAD

**Issue by JOE1994** [jblondin/csv-sniffer#1]
Hello :crab: ,
we (Rust group @sslab-gatech) found a memory-safety/soundness issue in this crate while scanning Rust code on crates.io for potential vulnerabilities.

## Issue Description
https://github.com/jblondin/csv-sniffer/blob/d964e42e207975fcb42777297c988c2cf2a014a7/src/snip.rs#L7-L18

`preamble_skipcount` method creates an uninitialized buffer (`buffer`) and passes it to user-provided `Read` implementation. This is unsound, because it allows safe Rust code to exhibit an undefined behavior (read from uninitialized memory).

[This part](https://doc.rust-lang.org/std/io/trait.Read.html#tymethod.read) from the `Read` trait documentation explains the issue:

> It is your responsibility to make sure that `buf` is initialized before calling `read`. Calling read with an uninitialized `buf` (of the kind one obtains via `MaybeUninit<T>`) is not safe, and can lead to undefined behavior.

## Suggested Fix

It is safe to zero-initialize the newly allocated `u8` buffer before read(), in order to prevent user-provided `Read` from accessing old contents of the newly allocated heap memory.

Thank you for checking out this issue :+1:

**Comment by jblondin** [comment]
Fixed by #2
